// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'AppsDownload': typeof import("../components/AppsDownload.vue")['default'],
    'ComparePlans': typeof import("../components/ComparePlans.vue")['default'],
    'Extension': typeof import("../components/Extension.vue")['default'],
    'FeatureCard': typeof import("../components/FeatureCard.vue")['default'],
    'FeatureCardRow': typeof import("../components/FeatureCardRow.vue")['default'],
    'FeatureRow': typeof import("../components/FeatureRow.vue")['default'],
    'FooterLinks': typeof import("../components/FooterLinks.vue")['default'],
    'Mission': typeof import("../components/Mission.vue")['default'],
    'OurJournery': typeof import("../components/OurJournery.vue")['default'],
    'PlanCard': typeof import("../components/PlanCard.vue")['default'],
    'PricingTab': typeof import("../components/PricingTab.vue")['default'],
    'SocialLinks': typeof import("../components/SocialLinks.vue")['default'],
    'SupportCard': typeof import("../components/SupportCard.vue")['default'],
    'Team': typeof import("../components/Team.vue")['default'],
    'TestimonialCard': typeof import("../components/TestimonialCard.vue")['default'],
    'TheAccordion': typeof import("../components/TheAccordion.vue")['default'],
    'TheApps': typeof import("../components/TheApps.vue")['default'],
    'TheBestFeature': typeof import("../components/TheBestFeature.vue")['default'],
    'TheButton': typeof import("../components/TheButton.vue")['default'],
    'TheClients': typeof import("../components/TheClients.vue")['default'],
    'TheContent': typeof import("../components/TheContent.vue")['default'],
    'TheCta': typeof import("../components/TheCta.vue")['default'],
    'TheDownload': typeof import("../components/TheDownload.vue")['default'],
    'TheFaq': typeof import("../components/TheFaq.vue")['default'],
    'TheFooter': typeof import("../components/TheFooter.vue")['default'],
    'TheHeader': typeof import("../components/TheHeader.vue")['default'],
    'TheHero': typeof import("../components/TheHero.vue")['default'],
    'TheLinkForm': typeof import("../components/TheLinkForm.vue")['default'],
    'TheLinkSteps': typeof import("../components/TheLinkSteps.vue")['default'],
    'TheNavigation': typeof import("../components/TheNavigation.vue")['default'],
    'ThePollSteps': typeof import("../components/ThePollSteps.vue")['default'],
    'TheReview': typeof import("../components/TheReview.vue")['default'],
    'TheRow': typeof import("../components/TheRow.vue")['default'],
    'TheSocialMediaCounter': typeof import("../components/TheSocialMediaCounter.vue")['default'],
    'TheSupport': typeof import("../components/TheSupport.vue")['default'],
    'TheTestimonial': typeof import("../components/TheTestimonial.vue")['default'],
    'TheUsersCounter': typeof import("../components/TheUsersCounter.vue")['default'],
    'VepaarStartup': typeof import("../components/VepaarStartup.vue")['default'],
    'VolizApp': typeof import("../components/VolizApp.vue")['default'],
    'IconsMdiCheckCircle': typeof import("../components/icons/MdiCheckCircle.vue")['default'],
    'IconsMdiClose': typeof import("../components/icons/MdiClose.vue")['default'],
    'IconsMdiMenu': typeof import("../components/icons/MdiMenu.vue")['default'],
    'IconsMdiMinus': typeof import("../components/icons/MdiMinus.vue")['default'],
    'IconsMdiPlus': typeof import("../components/icons/MdiPlus.vue")['default'],
    'IconsMdiReply': typeof import("../components/icons/MdiReply.vue")['default'],
    'IconsMdiTranslate': typeof import("../components/icons/MdiTranslate.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt3/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt3/dist/app/components/client-only")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
    'LazyAppsDownload': typeof import("../components/AppsDownload.vue")['default'],
    'LazyComparePlans': typeof import("../components/ComparePlans.vue")['default'],
    'LazyExtension': typeof import("../components/Extension.vue")['default'],
    'LazyFeatureCard': typeof import("../components/FeatureCard.vue")['default'],
    'LazyFeatureCardRow': typeof import("../components/FeatureCardRow.vue")['default'],
    'LazyFeatureRow': typeof import("../components/FeatureRow.vue")['default'],
    'LazyFooterLinks': typeof import("../components/FooterLinks.vue")['default'],
    'LazyMission': typeof import("../components/Mission.vue")['default'],
    'LazyOurJournery': typeof import("../components/OurJournery.vue")['default'],
    'LazyPlanCard': typeof import("../components/PlanCard.vue")['default'],
    'LazyPricingTab': typeof import("../components/PricingTab.vue")['default'],
    'LazySocialLinks': typeof import("../components/SocialLinks.vue")['default'],
    'LazySupportCard': typeof import("../components/SupportCard.vue")['default'],
    'LazyTeam': typeof import("../components/Team.vue")['default'],
    'LazyTestimonialCard': typeof import("../components/TestimonialCard.vue")['default'],
    'LazyTheAccordion': typeof import("../components/TheAccordion.vue")['default'],
    'LazyTheApps': typeof import("../components/TheApps.vue")['default'],
    'LazyTheBestFeature': typeof import("../components/TheBestFeature.vue")['default'],
    'LazyTheButton': typeof import("../components/TheButton.vue")['default'],
    'LazyTheClients': typeof import("../components/TheClients.vue")['default'],
    'LazyTheContent': typeof import("../components/TheContent.vue")['default'],
    'LazyTheCta': typeof import("../components/TheCta.vue")['default'],
    'LazyTheDownload': typeof import("../components/TheDownload.vue")['default'],
    'LazyTheFaq': typeof import("../components/TheFaq.vue")['default'],
    'LazyTheFooter': typeof import("../components/TheFooter.vue")['default'],
    'LazyTheHeader': typeof import("../components/TheHeader.vue")['default'],
    'LazyTheHero': typeof import("../components/TheHero.vue")['default'],
    'LazyTheLinkForm': typeof import("../components/TheLinkForm.vue")['default'],
    'LazyTheLinkSteps': typeof import("../components/TheLinkSteps.vue")['default'],
    'LazyTheNavigation': typeof import("../components/TheNavigation.vue")['default'],
    'LazyThePollSteps': typeof import("../components/ThePollSteps.vue")['default'],
    'LazyTheReview': typeof import("../components/TheReview.vue")['default'],
    'LazyTheRow': typeof import("../components/TheRow.vue")['default'],
    'LazyTheSocialMediaCounter': typeof import("../components/TheSocialMediaCounter.vue")['default'],
    'LazyTheSupport': typeof import("../components/TheSupport.vue")['default'],
    'LazyTheTestimonial': typeof import("../components/TheTestimonial.vue")['default'],
    'LazyTheUsersCounter': typeof import("../components/TheUsersCounter.vue")['default'],
    'LazyVepaarStartup': typeof import("../components/VepaarStartup.vue")['default'],
    'LazyVolizApp': typeof import("../components/VolizApp.vue")['default'],
    'LazyIconsMdiCheckCircle': typeof import("../components/icons/MdiCheckCircle.vue")['default'],
    'LazyIconsMdiClose': typeof import("../components/icons/MdiClose.vue")['default'],
    'LazyIconsMdiMenu': typeof import("../components/icons/MdiMenu.vue")['default'],
    'LazyIconsMdiMinus': typeof import("../components/icons/MdiMinus.vue")['default'],
    'LazyIconsMdiPlus': typeof import("../components/icons/MdiPlus.vue")['default'],
    'LazyIconsMdiReply': typeof import("../components/icons/MdiReply.vue")['default'],
    'LazyIconsMdiTranslate': typeof import("../components/icons/MdiTranslate.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt3/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt3/dist/app/components/client-only")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
  }
}
export const AppsDownload: typeof import("../components/AppsDownload.vue")['default']
export const ComparePlans: typeof import("../components/ComparePlans.vue")['default']
export const Extension: typeof import("../components/Extension.vue")['default']
export const FeatureCard: typeof import("../components/FeatureCard.vue")['default']
export const FeatureCardRow: typeof import("../components/FeatureCardRow.vue")['default']
export const FeatureRow: typeof import("../components/FeatureRow.vue")['default']
export const FooterLinks: typeof import("../components/FooterLinks.vue")['default']
export const Mission: typeof import("../components/Mission.vue")['default']
export const OurJournery: typeof import("../components/OurJournery.vue")['default']
export const PlanCard: typeof import("../components/PlanCard.vue")['default']
export const PricingTab: typeof import("../components/PricingTab.vue")['default']
export const SocialLinks: typeof import("../components/SocialLinks.vue")['default']
export const SupportCard: typeof import("../components/SupportCard.vue")['default']
export const Team: typeof import("../components/Team.vue")['default']
export const TestimonialCard: typeof import("../components/TestimonialCard.vue")['default']
export const TheAccordion: typeof import("../components/TheAccordion.vue")['default']
export const TheApps: typeof import("../components/TheApps.vue")['default']
export const TheBestFeature: typeof import("../components/TheBestFeature.vue")['default']
export const TheButton: typeof import("../components/TheButton.vue")['default']
export const TheClients: typeof import("../components/TheClients.vue")['default']
export const TheContent: typeof import("../components/TheContent.vue")['default']
export const TheCta: typeof import("../components/TheCta.vue")['default']
export const TheDownload: typeof import("../components/TheDownload.vue")['default']
export const TheFaq: typeof import("../components/TheFaq.vue")['default']
export const TheFooter: typeof import("../components/TheFooter.vue")['default']
export const TheHeader: typeof import("../components/TheHeader.vue")['default']
export const TheHero: typeof import("../components/TheHero.vue")['default']
export const TheLinkForm: typeof import("../components/TheLinkForm.vue")['default']
export const TheLinkSteps: typeof import("../components/TheLinkSteps.vue")['default']
export const TheNavigation: typeof import("../components/TheNavigation.vue")['default']
export const ThePollSteps: typeof import("../components/ThePollSteps.vue")['default']
export const TheReview: typeof import("../components/TheReview.vue")['default']
export const TheRow: typeof import("../components/TheRow.vue")['default']
export const TheSocialMediaCounter: typeof import("../components/TheSocialMediaCounter.vue")['default']
export const TheSupport: typeof import("../components/TheSupport.vue")['default']
export const TheTestimonial: typeof import("../components/TheTestimonial.vue")['default']
export const TheUsersCounter: typeof import("../components/TheUsersCounter.vue")['default']
export const VepaarStartup: typeof import("../components/VepaarStartup.vue")['default']
export const VolizApp: typeof import("../components/VolizApp.vue")['default']
export const IconsMdiCheckCircle: typeof import("../components/icons/MdiCheckCircle.vue")['default']
export const IconsMdiClose: typeof import("../components/icons/MdiClose.vue")['default']
export const IconsMdiMenu: typeof import("../components/icons/MdiMenu.vue")['default']
export const IconsMdiMinus: typeof import("../components/icons/MdiMinus.vue")['default']
export const IconsMdiPlus: typeof import("../components/icons/MdiPlus.vue")['default']
export const IconsMdiReply: typeof import("../components/icons/MdiReply.vue")['default']
export const IconsMdiTranslate: typeof import("../components/icons/MdiTranslate.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt3/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt3/dist/app/components/client-only")['default']
export const NuxtLink: typeof import("../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
export const LazyAppsDownload: typeof import("../components/AppsDownload.vue")['default']
export const LazyComparePlans: typeof import("../components/ComparePlans.vue")['default']
export const LazyExtension: typeof import("../components/Extension.vue")['default']
export const LazyFeatureCard: typeof import("../components/FeatureCard.vue")['default']
export const LazyFeatureCardRow: typeof import("../components/FeatureCardRow.vue")['default']
export const LazyFeatureRow: typeof import("../components/FeatureRow.vue")['default']
export const LazyFooterLinks: typeof import("../components/FooterLinks.vue")['default']
export const LazyMission: typeof import("../components/Mission.vue")['default']
export const LazyOurJournery: typeof import("../components/OurJournery.vue")['default']
export const LazyPlanCard: typeof import("../components/PlanCard.vue")['default']
export const LazyPricingTab: typeof import("../components/PricingTab.vue")['default']
export const LazySocialLinks: typeof import("../components/SocialLinks.vue")['default']
export const LazySupportCard: typeof import("../components/SupportCard.vue")['default']
export const LazyTeam: typeof import("../components/Team.vue")['default']
export const LazyTestimonialCard: typeof import("../components/TestimonialCard.vue")['default']
export const LazyTheAccordion: typeof import("../components/TheAccordion.vue")['default']
export const LazyTheApps: typeof import("../components/TheApps.vue")['default']
export const LazyTheBestFeature: typeof import("../components/TheBestFeature.vue")['default']
export const LazyTheButton: typeof import("../components/TheButton.vue")['default']
export const LazyTheClients: typeof import("../components/TheClients.vue")['default']
export const LazyTheContent: typeof import("../components/TheContent.vue")['default']
export const LazyTheCta: typeof import("../components/TheCta.vue")['default']
export const LazyTheDownload: typeof import("../components/TheDownload.vue")['default']
export const LazyTheFaq: typeof import("../components/TheFaq.vue")['default']
export const LazyTheFooter: typeof import("../components/TheFooter.vue")['default']
export const LazyTheHeader: typeof import("../components/TheHeader.vue")['default']
export const LazyTheHero: typeof import("../components/TheHero.vue")['default']
export const LazyTheLinkForm: typeof import("../components/TheLinkForm.vue")['default']
export const LazyTheLinkSteps: typeof import("../components/TheLinkSteps.vue")['default']
export const LazyTheNavigation: typeof import("../components/TheNavigation.vue")['default']
export const LazyThePollSteps: typeof import("../components/ThePollSteps.vue")['default']
export const LazyTheReview: typeof import("../components/TheReview.vue")['default']
export const LazyTheRow: typeof import("../components/TheRow.vue")['default']
export const LazyTheSocialMediaCounter: typeof import("../components/TheSocialMediaCounter.vue")['default']
export const LazyTheSupport: typeof import("../components/TheSupport.vue")['default']
export const LazyTheTestimonial: typeof import("../components/TheTestimonial.vue")['default']
export const LazyTheUsersCounter: typeof import("../components/TheUsersCounter.vue")['default']
export const LazyVepaarStartup: typeof import("../components/VepaarStartup.vue")['default']
export const LazyVolizApp: typeof import("../components/VolizApp.vue")['default']
export const LazyIconsMdiCheckCircle: typeof import("../components/icons/MdiCheckCircle.vue")['default']
export const LazyIconsMdiClose: typeof import("../components/icons/MdiClose.vue")['default']
export const LazyIconsMdiMenu: typeof import("../components/icons/MdiMenu.vue")['default']
export const LazyIconsMdiMinus: typeof import("../components/icons/MdiMinus.vue")['default']
export const LazyIconsMdiPlus: typeof import("../components/icons/MdiPlus.vue")['default']
export const LazyIconsMdiReply: typeof import("../components/icons/MdiReply.vue")['default']
export const LazyIconsMdiTranslate: typeof import("../components/icons/MdiTranslate.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt3/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt3/dist/app/components/client-only")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
